"""Created reminder of medicine

Revision ID: 03d9d3ebb83d
Revises: cd20f0ff503d
Create Date: 2025-09-07 22:18:58.137018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d9d3ebb83d'
down_revision: Union[str, Sequence[str], None] = 'cd20f0ff503d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_reminders',
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('remind_time', sa.Time(), nullable=False),
    sa.Column('repeat_daily', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_reminders')
    # ### end Alembic commands ###
