"""add coordinates field to hospitals

Revision ID: 39e9d23caa46
Revises: 5c81fb101cab
Create Date: 2025-08-15 12:42:10.721148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e9d23caa46'
down_revision: Union[str, Sequence[str], None] = '5c81fb101cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('coordinates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'coordinates')
    # ### end Alembic commands ###
