"""added user details

Revision ID: 3eef8ed2f87f
Revises: ab7e9630011e
Create Date: 2025-08-03 12:45:12.578786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eef8ed2f87f'
down_revision: Union[str, Sequence[str], None] = 'ab7e9630011e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('district_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('blood_sugar_mg_dl', sa.Float(), nullable=True),
    sa.Column('bp_systolic_mm_hg', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic_mm_hg', sa.Integer(), nullable=True),
    sa.Column('cholesterol_mg_dl', sa.Float(), nullable=True),
    sa.Column('hemoglobin_g_dl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###
