"""Add phone_number to hospitals table

Revision ID: 512bea5a4c2c
Revises: 56d6e61af52f
Create Date: 2025-08-27 01:28:00.962777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512bea5a4c2c'
down_revision: Union[str, Sequence[str], None] = '56d6e61af52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'phone_number')
    # ### end Alembic commands ###
