"""Add hospital admin, doctor working hours, services table

Revision ID: 5c81fb101cab
Revises: 82d96ab37850
Create Date: 2025-08-10 12:27:36.593317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c81fb101cab"
down_revision: Union[str, Sequence[str], None] = "82d96ab37850"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("hospital_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("doctor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "doctors",
        sa.Column(
            "working_hours", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "hospitals", sa.Column("admin_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "hospitals", "users", ["admin_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "queues", sa.Column("appointment_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "queues", sa.Column("appointment_start", sa.DateTime(), nullable=False)
    )
    op.add_column("queues", sa.Column("appointment_end", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queues", "appointment_end")
    op.drop_column("queues", "appointment_start")
    op.drop_column("queues", "appointment_date")
    op.drop_constraint(None, "hospitals", type_="foreignkey")
    op.drop_column("hospitals", "admin_id")
    op.drop_column("doctors", "working_hours")
    op.drop_table("services")
    # ### end Alembic commands ###
