"""added photo and chat histroy

Revision ID: 82d96ab37850
Revises: 3eef8ed2f87f
Create Date: 2025-08-03 14:38:08.776054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82d96ab37850'
down_revision: Union[str, Sequence[str], None] = '3eef8ed2f87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('doctors', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('reyting', sa.Float(), nullable=True))
    op.add_column('hospitals', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('hospitals', sa.Column('reyting', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'reyting')
    op.drop_column('hospitals', 'photo')
    op.drop_column('doctors', 'reyting')
    op.drop_column('doctors', 'photo')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_column('chat_history', 'user_id')
    # ### end Alembic commands ###
