"""removed nullable false from roles in users

Revision ID: dcb8b8ac74a4
Revises: 9b11617f572f
Create Date: 2025-07-27 02:25:31.935712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcb8b8ac74a4"
down_revision: Union[str, Sequence[str], None] = "9b11617f572f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
